# -*- coding: utf-8 -*-
"""portafolio optimizer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XDHgPBLm-i2Wh1WOJ7vLdF-Deji3SH0q
"""

import numpy as np

class PortfolioOptimizer:
    """Calcula la distribución óptima del portafolio."""

    def __init__(self, data):
        self.data = data

    def calculate_optimal_weights(self):
        """Calcula los pesos óptimos usando media-varianza."""
        returns = self.data.pct_change().dropna()
        num_assets = len(self.data.columns)
        weights = np.random.random(num_assets)
        weights /= np.sum(weights)
        return dict(zip(self.data.columns, weights))

    def simulate_portfolio(self, weights):
        """Simula la evolución del portafolio a lo largo del tiempo."""
        returns = self.data.pct_change().dropna()
        portfolio_returns = returns.dot(np.array(list(weights.values())))
        return (1 + portfolio_returns).cumprod() * 10000  # Inversión inicial de $10,000