# -*- coding: utf-8 -*-
"""report_generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1frpZMsIUTfPaH2ul3SGuGIlzbo7O_z4g
"""

from fpdf import FPDF

def generar_reporte_pdf(indice, moneda, monto_inversion, df_weights, risk_free_rate, objetivo, filename="reporte_portafolio.pdf"):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)

    # Título
    pdf.cell(200, 10, txt="Reporte de Optimización del Portafolio", ln=True, align='C')
    pdf.ln(10)

    # Datos generales
    pdf.cell(200, 10, txt=f"Índice de referencia: {indice}", ln=True)
    pdf.cell(200, 10, txt=f"Moneda de inversión: {moneda}", ln=True)
    pdf.cell(200, 10, txt=f"Monto de inversión: {monto_inversion:.2f} {moneda}", ln=True)
    pdf.cell(200, 10, txt=f"Tasa libre de riesgo: {risk_free_rate:.2%}", ln=True)
    pdf.cell(200, 10, txt=f"Objetivo de optimización: {objetivo}", ln=True)
    pdf.ln(10)

    # Tabla de distribución del portafolio
    pdf.cell(60, 10, txt="Activo", border=1, align='C')
    pdf.cell(40, 10, txt="Peso (%)", border=1, align='C')
    pdf.cell(50, 10, txt="Inversión ({})".format(moneda), border=1, align='C')
    pdf.ln()

    for _, row in df_weights.iterrows():
        pdf.cell(60, 10, txt=row["Activo"], border=1)
        pdf.cell(40, 10, txt=f"{row['Peso']*100:.2f}", border=1, align='C')
        pdf.cell(50, 10, txt=f"{row['Inversión']:.2f}", border=1, align='C')
        pdf.ln()

    pdf.ln(10)
    pdf.cell(200, 10, txt="Este reporte ha sido generado automáticamente.", ln=True, align='C')

    # Guardar PDF
    pdf.output(filename)
    print(f"Reporte guardado en {filename}")