# -*- coding: utf-8 -*-
"""user params v1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q__Vnx_5zmhEefm9FBLsH8fV7XsQ4zdd
"""

def obtener_parametros_usuario():
    indices = ["S&P 500 (EE.UU.)", "FTSE 100 (Reino Unido)", "Nikkei 225 (Japón)", "S&P/BMV IPC (México)"]
    monedas = ["USD", "GBP", "JPY", "MXN"]
    horizontes = ["1 año", "5 años", "10 años"]
    objetivos = ["Índice Sharpe", "Retorno máximo", "Riesgo mínimo"]

    print("Selecciona los parámetros para tu portafolio:")
    indice = int(input("Índice de referencia (1. S&P 500, 2. FTSE 100, 3. Nikkei 225, 4. S&P/BMV IPC): ")) - 1
    moneda = monedas[indice]
    objetivo = int(input("Objetivo de optimización (1. Índice Sharpe, 2. Retorno máximo, 3. Riesgo mínimo): ")) - 1
    horizonte = int(input("Horizonte de inversión (1. 1 año, 2. 5 años, 3. 10 años): ")) - 1

    return indices[indice], moneda, horizontes[horizonte], objetivos[objetivo]