# -*- coding: utf-8 -*-
"""visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pLd6BVKd7PUu1Xti5Ts9shJLpgwsH9NK
"""

import matplotlib.pyplot as plt

def plot_portfolio_growth(growth):
    """Genera un gráfico de crecimiento del portafolio."""
    plt.figure(figsize=(10, 5))
    plt.plot(growth, label="Crecimiento del Portafolio")
    plt.xlabel("Fecha")
    plt.ylabel("Valor del Portafolio")
    plt.legend()
    plt.show()